name: pwm_controller
description: Управление ШИМ по BLE
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.6.0  # или последняя версия

flutter:
  uses-material-design: true
